### ISSUE TITLE
Heroku HTTP break Get User Media

### ISSUE THREAD

**Issue by enricop89** [nexmo-se/video-api-multiparty-toolkit-sample-app#31]
If the user navigates on the HTTP website and not HTTPS, the get user media fails. We should add the accessDenied event and catch the error. 

We also need to show an alert to the user

**Comment by javiermolsanz** [comment]
Should be resolved in https://github.com/nexmo-se/video-api-multiparty-toolkit-sample-app/pull/58

I've taken a different approach as we discussed. If the user navigates to HTTP, we redirect to HTTPs
